#!/bin/env bash
if (yt-dlp -o '~/Videos/%(title)s.%(ext)s' $(wl-paste)); then
  hyprctl notify 5 4000 "rgb(0000ff)" " Video saved in ~/Videos"
else
  hyprctl notify 3 4000 "rgb(ff0000)" " Error while downloading a video"
fi
